name: near_api_dart
description:  A library to interact with NEAR RPC endpoints.
version: 0.0.1
repository: https://github.com/0xdir/near_api_dart

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
